version: 2
jobs:
  deploy:
    docker:
    - image: convox/circleci
    working_directory: ~/convox
    steps:
    - checkout
    - run:
        command: mkdir -p workspace
    - run:
        name: Deploy Application
        environment:
          CONVOX_HOST: console.convox.com
          CONVOX_RACK: david/ecs
        command: convox deploy --app $CIRCLE_PROJECT_REPONAME
workflows:
  deploy:
    jobs:
    - deploy
  version: 2
